spring.application.name=college-management-system
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/college_management_db
spring.data.mongodb.auto-index-creation=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

logging.level.root=INFO
logging.level.com.college.management=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
